### ISSUE TITLE
Feature Request: front-matter support

### ISSUE THREAD

**Issue by git-no** [pablo-abc/svelte-markdown#46]
A feature request would be the support of front-matter in svelte-markdown.
My markdown file has a `{title}`from front-matter but does not resolve the value.

**Comment by pablo-abc** [comment]
Sorry for the delay! Front-matter's purpose is to add metadata that will not necessarily be rendered to your markdown. Adding templating behaviour like this feels out of scope for this package. Specially since it's a feature not provided/expected from most markdown parsers. I'll be closing this since the only objective of this package is to render markdown as Svelte components.
