### ISSUE TITLE
warning message if the markdown getting rendered

### ISSUE THREAD

**Issue by vikbert** [pablo-abc/svelte-markdown#5]
Can you have a look at this issue, why do these warning thrown during the markdown getting rendered in dev mode?

<img width="1043" alt="Bildschirmfoto 2021-03-06 um 09 48 34" src="https://user-images.githubusercontent.com/3229226/110201045-5ea91980-7e61-11eb-8304-2de70aba9284.png">

**Comment by pablo-abc** [comment]
This is just a dev warning coming from Svelte, not this package, that shouldn't affect your code itself so it can be safely ignored. It's annoying, I know and it seems to be a [still unsolved issue in the Svelte repo itself](https://github.com/sveltejs/svelte/issues/4652). 

I'm still trying to look for a workaround for this, but the reason that this props are being passed is due to you being able to replace any renderer with your own component, and they're something you might want to use when building your component even though they're not being used by the default ones.

**Comment by vikbert** [comment]
hi pablo,
thx for the quick feedback. Yes, you are right. The issues are only in dev mode, and will not be shown in production build. Sure I can live with them 💯 thx for your nice work on svelte-markdown.

**Comment by togglydev** [comment]
A potential workaround would be to have all the inbuilt components just declare const raw and text and then not use them. Not very pretty, of course.
